#!/bin/bash
echo "============= User Baru =============="
read -p " -Masukan Username   : " Login
read -p " -Masukan Password   : " Pass
read -p " -Masa Aktif         : " masaaktif

d=$(cat /root/domain.txt)
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo -e "===============Informasi SSH Account============="
echo -e "Domain         : $d"
echo -e "Host           : $myip" 
echo -e "Port OpenSSH   : 22,143"
echo -e "Port Dropbear  : 80,444"
echo -e "Port SSL/TLS   : 443"
echo -e "Port Squid     : 8080,3128"
echo -e "Config OpenVPN (TCP 1194): http://$d:81/client.ovpn"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo -e "-----------------------------------"
echo -e "Aktif Sampai: $exp"
echo -e "==================================="
echo -e "*** Diyan Santoso ***"
